schema = (
  'DATA_MART_NAME',
  'DATA_MART_STATUS',
  'JOB_COUNT',
  'JOBS_FINISHED',
  'DATA_MART_START_DTTM',
  'DATA_MART_END_DTTM',
  'RUN_TIME_TO_CURRENT_DATA_MART_STATUS',
  'DATA_MART_TRANS_RATE'
)
