--  C8_MWH.ETL_ENGINE_HISTORY_DDL.sql

-- sqlcmd -S localhost -U sa -P 1F0rg0t1 -i  C8_MWH.ETL_ENGINE_HISTORY_DDL.sql

use UMA_DWH
GO



IF EXISTS (SELECT * FROM sys.objects so JOIN  sys.schemas ss on (so.schema_id = ss.schema_id) WHERE so.type = 'U' AND so.name = 'ETL_ENGINE_HISTORY' and ss.name = 'MWH')

       DROP TABLE MWH.ETL_ENGINE_HISTORY

GO

 

CREATE TABLE [MWH].[ETL_ENGINE_HISTORY](

       [ID] [int] IDENTITY(1,1) NOT NULL,

       [INSERT_DTTM] [datetime] NOT NULL,

       [UPDATE_DTTM] [datetime] NOT NULL,

       [DONE_DTTM] [datetime]  NULL,

       [LST_MOD_USER] [varchar](80) NOT NULL,

       [ENGINE_STATUS] [varchar](200)  NULL,

       [ENGINE_MESSAGE]  [varchar](80)  NULL,

       [PROCEDURE_NAME] [varchar](80)  NULL,

       [DATA_MART_NAME] [varchar](80)  NULL,

       [PRIORITY] [smallint]  NULL,

CONSTRAINT [PK_ETL_ENGINE_HISTORY] PRIMARY KEY NONCLUSTERED

(

       [ID] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY]

) ON [PRIMARY]

 

GO

 

ALTER TABLE [MWH].[ETL_ENGINE_HISTORY] ADD  CONSTRAINT [ETL_ENGINE_HISTORY_INSERT_DTTM_DF]  DEFAULT (getdate()) FOR [INSERT_DTTM]

GO

 

ALTER TABLE [MWH].[ETL_ENGINE_HISTORY] ADD  CONSTRAINT [ETL_ENGINE_HISTORY_UPDATE_DTTM_DF]  DEFAULT (getdate()) FOR [UPDATE_DTTM]

GO

 

ALTER TABLE [MWH].[ETL_ENGINE_HISTORY] ADD  CONSTRAINT [ETL_ENGINE_HISTORY_LST_MOD_USER_DF]  DEFAULT (user_name()) FOR [LST_MOD_USER]

GO

 

 

CREATE TRIGGER MWH.ETL_ENGINE_HISTORY_UD_TRIG

ON MWH.ETL_ENGINE_HISTORY

AFTER UPDATE

AS  BEGIN

    UPDATE MWH.ETL_ENGINE_HISTORY

    SET UPDATE_DTTM = GETDATE()

    WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)

END

GO