--  C8_UMA_TELECOM.D_REP_ERROR



IF EXISTS (SELECT * FROM sys.objects so JOIN  sys.schemas ss on (so.schema_id = ss.schema_id) WHERE so.type = 'U' AND so.name = 'D_REP_ERROR' and ss.name = 'UMA_TELECOM')
	DROP TABLE UMA_TELECOM.D_REP_ERROR
GO

CREATE TABLE UMA_TELECOM.D_REP_ERROR(
		ID INT NOT NULL IDENTITY (1,1),
		INSERT_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_ERROR_INSERT_DTTM_DF DEFAULT getdate() NOT NULL,
		UPDATE_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_ERROR_UPDATE_DTTM_DF DEFAULT getdate() NOT NULL,
		LST_MOD_USER VARCHAR(80) CONSTRAINT UMA_TELECOM_D_REP_ERROR_LST_MOD_USER_DF DEFAULT user_name() NOT NULL,
		MSTR_LOAD_ID INT CONSTRAINT UMA_TELECOM_D_REP_ERROR_MSTR_LOAD_ID_DF DEFAULT (-1) NOT NULL,
		REP_ID					integer			 NULL,
		REP_userId				VARCHAR(100)	  NULL,
		REP_homeSite_ID			integer			  NULL,   
		REP_firstName			VARCHAR(100)	 NULL,
		REP_lastName			VARCHAR(100)	 NULL,
		REP_displayName			VARCHAR(100)	Null,
		REP_ntDomainUser		VARCHAR(100)	NULL,
		REP_extension			VARCHAR(100)	NULL,
		REP_outboundANI			VARCHAR(100)	NULL,
		REP_id_LIST				VARCHAR(800)	NULL,
		REP_customAttributes	VARCHAR(100)	NULL,
		REP_dateAdded			datetime

 CONSTRAINT PK_UMA_TELECOM_D_REP_ERROR		PRIMARY KEY NONCLUSTERED 
(
		ID				ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO



CREATE TRIGGER UMA_TELECOM.D_REP_ERROR_UD_TRIG
ON UMA_TELECOM.D_REP_ERROR
AFTER UPDATE
AS  BEGIN
    UPDATE UMA_TELECOM.D_REP_ERROR
    SET UPDATE_DTTM = GETDATE()
    WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)
END
GO

