--  C8_UMA_TELECOM.D_REP_ROLE.sql
use UMA_DWH
go

--create schema UMA_TELECOM
-- go



--  C8_UMA_TELECOM.D_REP.sql

/*
Roles one to many relationship

$id: integer,
roleId: string,
name: string,
id: integer(Figure out the reason this is always set to 0),
dateAdded: datetime
*/


--select  REP_ROLE_roleId, REP_ROLE_name, count(*)  from  UMA_TELECOM.D_REP_ROLE  group by   REP_ROLE_roleId, REP_ROLE_name

--select * from UMA_TELECOM.D_REP_ROLE



IF EXISTS (SELECT * FROM sys.objects so JOIN  sys.schemas ss on (so.schema_id = ss.schema_id) WHERE so.type = 'U' AND so.name = 'D_REP_ROLE' and ss.name = 'UMA_TELECOM')
	DROP TABLE UMA_TELECOM.D_REP_ROLE
GO

IF EXISTS (SELECT * FROM sys.objects so JOIN  sys.schemas ss on (so.schema_id = ss.schema_id) WHERE so.type = 'U' AND so.name = 'X_REP_TO_REP_ROLE' and ss.name = 'UMA_TELECOM')
	DROP TABLE UMA_TELECOM.X_REP_TO_REP_ROLE
GO




CREATE TABLE UMA_TELECOM.X_REP_TO_REP_ROLE(
		ID INT NOT NULL IDENTITY (1,1),
		INSERT_DTTM DATETIME CONSTRAINT UMA_TELECOM_X_REP_TO_REP_ROLE_INSERT_DTTM_DF DEFAULT getdate() NOT NULL,
		UPDATE_DTTM DATETIME CONSTRAINT UMA_TELECOM_X_REP_TO_REP_ROLE_UPDATE_DTTM_DF DEFAULT getdate() NOT NULL,
		LST_MOD_USER VARCHAR(80) CONSTRAINT UMA_TELECOM_X_REP_TO_REP_ROLE_LST_MOD_USER_DF DEFAULT user_name() NOT NULL,
		MSTR_LOAD_ID INT CONSTRAINT UMA_TELECOM_X_REP_TO_REP_ROLE_MSTR_LOAD_ID_DF DEFAULT (-1) NOT NULL,
		D_REP_ID					integer			NOT NULL,
		D_REP_ROLE_ID				integer			NOT NULL,
		REP_ROLE_ID					integer			NOT NULL,
		REP_ROLE_dateAdded			datetime2		NOT NULL,
		REP_ROLE_dateRemoved		datetime2		NULL,
 CONSTRAINT PK_UMA_TELECOM_X_REP_TO_REP_ROLE		PRIMARY KEY NONCLUSTERED 
(
		ID				ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO



CREATE NONCLUSTERED INDEX  UMA_TELECOM_D_REP_ROLE_IDX01   on UMA_TELECOM.X_REP_TO_REP_ROLE 
(
		ID				ASC,
		D_REP_ID		ASC,
		D_REP_ROLE_ID	ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX  UMA_TELECOM_D_REP_ROLE_IDX02   on UMA_TELECOM.X_REP_TO_REP_ROLE 
(
		
		D_REP_ID		ASC,
		D_REP_ROLE_ID	ASC,
		ID				ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX  UMA_TELECOM_D_REP_ROLE_IDX03   on UMA_TELECOM.X_REP_TO_REP_ROLE 
(
		
		REP_ROLE_dateRemoved  asc,
		D_REP_ID		ASC,
		D_REP_ROLE_ID	ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



CREATE TRIGGER UMA_TELECOM.X_REP_TO_REP_ROLE_UD_TRIG
ON UMA_TELECOM.X_REP_TO_REP_ROLE
AFTER UPDATE
AS  BEGIN
    UPDATE UMA_TELECOM.X_REP_TO_REP_ROLE
    SET UPDATE_DTTM = GETDATE()
    WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)
END
GO









CREATE TABLE UMA_TELECOM.D_REP_ROLE(
		ID INT NOT NULL IDENTITY (1,1),
		INSERT_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_ROLE_INSERT_DTTM_DF DEFAULT getdate() NOT NULL,
		UPDATE_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_ROLE_UPDATE_DTTM_DF DEFAULT getdate() NOT NULL,
		LST_MOD_USER VARCHAR(80) CONSTRAINT UMA_TELECOM_D_REP_ROLE_LST_MOD_USER_DF DEFAULT user_name() NOT NULL,
		MSTR_LOAD_ID INT CONSTRAINT UMA_TELECOM_D_REP_ROLE_MSTR_LOAD_ID_DF DEFAULT (-1) NOT NULL,
		REP_ROLE_roleId				nVARCHAR(100)	NOT NULL,
		REP_ROLE_name				nVARCHAR(100)	NOT NULL
 CONSTRAINT PK_UMA_TELECOM_D_REP_ROLE		PRIMARY KEY NONCLUSTERED 
(
		ID				ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO



CREATE NONCLUSTERED INDEX  UMA_TELECOM_D_REP_ROLE_IDX01   on UMA_TELECOM.D_REP_ROLE 
(
		ID				ASC,
		REP_ROLE_name		ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX  UMA_TELECOM_D_REP_ROLE_IDX02   on UMA_TELECOM.D_REP_ROLE 
(
		REP_ROLE_name		ASC,
		REP_ROLE_roleId     ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



CREATE UNIQUE INDEX  UMA_TELECOM_D_REP_ROLE_IDX03   on UMA_TELECOM.D_REP_ROLE 
(
		REP_ROLE_name		ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



CREATE TRIGGER UMA_TELECOM.D_REP_ROLE_UD_TRIG
ON UMA_TELECOM.D_REP_ROLE
AFTER UPDATE
AS  BEGIN
    UPDATE UMA_TELECOM.D_REP_ROLE
    SET UPDATE_DTTM = GETDATE()
    WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)
END
GO


