--  C8_UMA_TELECOM.D_REP.sql
use UMA_DWH
go

--create schema UMA_TELECOM
-- go


IF EXISTS (SELECT * FROM sys.objects so JOIN  sys.schemas ss on (so.schema_id = ss.schema_id) WHERE so.type = 'U' AND so.name = 'D_REP' and ss.name = 'UMA_TELECOM')
	DROP TABLE UMA_TELECOM.D_REP
GO
--  C8_UMA_TELECOM.D_REP.sql


IF EXISTS (SELECT * FROM sys.objects so JOIN  sys.schemas ss on (so.schema_id = ss.schema_id) WHERE so.type = 'U' AND so.name = 'D_REP_homeSite' and ss.name = 'UMA_TELECOM')
	DROP TABLE UMA_TELECOM.D_REP_homeSite
GO

CREATE TABLE UMA_TELECOM.D_REP_homeSite(
		ID INT NOT NULL IDENTITY (1,1),
		INSERT_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_homeSite_INSERT_DTTM_DF DEFAULT getdate() NOT NULL,
		UPDATE_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_homeSite_UPDATE_DTTM_DF DEFAULT getdate() NOT NULL,
		LST_MOD_USER VARCHAR(80) CONSTRAINT UMA_TELECOM_D_REP_homeSite_LST_MOD_USER_DF DEFAULT user_name() NOT NULL,
		MSTR_LOAD_ID INT CONSTRAINT UMA_TELECOM_D_REP_homeSite_MSTR_LOAD_ID_DF DEFAULT (-1) NOT NULL,
		REP_homeSite_ID					INTEGER CONSTRAINT UMA_TELECOM_D_REP_homeSite_ID_DF DEFAULT (0) NOT NULL,
		HomeSite_Name					nvarchar(20)	 NULL,
 CONSTRAINT PK_UMA_TELECOM_D_REP_homeSite		PRIMARY KEY NONCLUSTERED 
(
		ID				ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO


INSERT into UMA_TELECOM.D_REP_homeSite (REP_homeSite_ID, HomeSite_Name)
values  (0 , 'N/A');

INSERT into UMA_TELECOM.D_REP_homeSite (REP_homeSite_ID, HomeSite_Name)
values  (101 , 'Legacy');

INSERT into UMA_TELECOM.D_REP_homeSite (REP_homeSite_ID, HomeSite_Name)
values  (102 , 'MCS');

INSERT into UMA_TELECOM.D_REP_homeSite (REP_homeSite_ID, HomeSite_Name)
values  (103 , 'FRS');

INSERT into UMA_TELECOM.D_REP_homeSite (REP_homeSite_ID, HomeSite_Name)
values  (201 , 'BTB');


--  select * from UMA_TELECOM.D_REP_homeSite




CREATE TABLE UMA_TELECOM.D_REP(
		ID INT NOT NULL IDENTITY (1,1),
		INSERT_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_INSERT_DTTM_DF DEFAULT getdate() NOT NULL,
		UPDATE_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_UPDATE_DTTM_DF DEFAULT getdate() NOT NULL,
		LST_MOD_USER VARCHAR(80) CONSTRAINT UMA_TELECOM_D_REP_LST_MOD_USER_DF DEFAULT user_name() NOT NULL,
		MSTR_LOAD_ID INT CONSTRAINT UMA_TELECOM_D_REP_MSTR_LOAD_ID_DF DEFAULT (-1) NOT NULL,
		REP_ID					integer			 NULL,
		REP_userId				nvarchar(300)	 NOT NULL,
		REP_homeSite_ID			integer			 CONSTRAINT UMA_TELECOM_D_REP_homeSite_DF DEFAULT 0 NOT NULL,   
		REP_firstName			nvarchar(max)	 NULL,
		REP_lastName			nvarchar(max)	 NULL,
		REP_displayName			nvarchar(max)	Null,
		REP_ntDomainUser		nvarchar(max)	NULL,
		REP_extension			nvarchar(max)	NULL,
		REP_outboundANI			nvarchar(max)	NULL,
		REP_id_LIST				nvarchar(max)	NULL,
		REP_customAttributes	nvarchar(max)	NULL,
		REP_dateAdded			datetime2

 CONSTRAINT PK_UMA_TELECOM_D_REP		PRIMARY KEY NONCLUSTERED 
(
		ID				ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO



CREATE NONCLUSTERED INDEX  UMA_TELECOM_D_REP_IDX01 on UMA_TELECOM.D_REP 
(
		ID				ASC,
		REP_dateAdded		ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE UNIQUE INDEX  UMA_TELECOM_D_REP_IDX02 on UMA_TELECOM.D_REP 
(
		REP_userId				ASC,
		REP_dateAdded		ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE UNIQUE INDEX  UMA_TELECOM_D_REP_IDX03 on UMA_TELECOM.D_REP 
(
		REP_userId				ASC,
		REP_homeSite_ID			ASC,
		REP_dateAdded			asc
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE TRIGGER UMA_TELECOM.D_REP_UD_TRIG
ON UMA_TELECOM.D_REP
AFTER UPDATE
AS  BEGIN
    UPDATE UMA_TELECOM.D_REP
    SET UPDATE_DTTM = GETDATE()
    WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)
END
GO




IF EXISTS (SELECT * FROM sys.objects so JOIN  sys.schemas ss on (so.schema_id = ss.schema_id) WHERE so.type = 'U' AND so.name = 'D_REP_HomeSite_Hist' and ss.name = 'UMA_TELECOM')
	DROP TABLE UMA_TELECOM.D_REP_HomeSite_Hist
GO



CREATE TABLE UMA_TELECOM.D_REP_HomeSite_Hist(
		ID INT NOT NULL IDENTITY (1,1),
		INSERT_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_HomeSite_Hist_INSERT_DTTM_DF DEFAULT getdate() NOT NULL,
		UPDATE_DTTM DATETIME CONSTRAINT UMA_TELECOM_D_REP_HomeSite_Hist_UPDATE_DTTM_DF DEFAULT getdate() NOT NULL,
		LST_MOD_USER VARCHAR(80) CONSTRAINT UMA_TELECOM_D_REP_HomeSite_Hist_LST_MOD_USER_DF DEFAULT user_name() NOT NULL,
		MSTR_LOAD_ID INT CONSTRAINT UMA_TELECOM_D_REP_HomeSite_Hist_MSTR_LOAD_ID_DF DEFAULT (-1) NOT NULL,
		D_REP_ID				integer			NOT NULL,
		REP_homeSite_ID			integer			 CONSTRAINT UMA_TELECOM_D_REP_homeSite_ID_DF2 DEFAULT 0 NOT NULL, 
		REP_dateAdded			datetime2,  
 CONSTRAINT PK_UMA_TELECOM_D_REP_HomeSite_Hist_PK		PRIMARY KEY NONCLUSTERED 
(
		ID				ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE UNIQUE INDEX  UMA_TELECOM_D_REP_HomeSite_Hist_IDX01 on UMA_TELECOM.D_REP_HomeSite_Hist
(
		D_REP_ID				ASC,
		REP_homeSite_ID		ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE TRIGGER UMA_TELECOM.D_REP_HomeSite_Hist_UD_TRIG
ON UMA_TELECOM.D_REP_HomeSite_Hist
AFTER UPDATE
AS  BEGIN
    UPDATE UMA_TELECOM.D_REP_HomeSite_Hist
    SET UPDATE_DTTM = GETDATE()
    WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)
END
GO