USE [UMA_DWH]
GO

DROP TABLE [MWH].[ETL_HISTORY]
GO
 
/****** Object:  Table [MWH].[ETL_HISTORY]    Script Date: 3/30/2018 8:21:28 AM ******/
SET ANSI_NULLS ON
GO
 
SET QUOTED_IDENTIFIER ON
GO
 
CREATE TABLE [MWH].[ETL_HISTORY](
       [ID] [int] NOT NULL,
       [START_DTTM] [datetime] NULL,
       [END_DTTM] [datetime] NULL,
       [STATUS] [varchar](30) NOT NULL,
       [SOURCE_SERVER_NAME] [varchar](60) NOT NULL,
       [SOURCE_DB_NAME] [varchar](40) NOT NULL,
       [SOURCE_SCHEMA_NAME] [varchar](40) NOT NULL,
       [SOURCE_TABLE_NAME] [varchar](60) NOT NULL,
       [TARGET_SCHEMA_NAME] [varchar](40) NOT NULL,
       [TARGET_TABLE_NAME] [varchar](60) NOT NULL,
       [CALLING_PROC] [varchar](120) NOT NULL,
       [SP_PARM_1] [varchar](30) NULL,
       [SP_PARM_2] [varchar](30) NULL,
       [INSERT_CNT] [int] NULL,
       [UPDATE_CNT] [int] NULL,
       [RUN_TIME_SEC] [int] NULL,
       [LST_MOD_USER] [varchar](80) NULL,
       [INSERT_DTTM] [datetime] NULL,
       [UPDATE_DTTM] [datetime] NULL,
       [engine_message] [varchar](800) NULL,
       [ERR_NUM] [int] NULL,
       [DELETE_CNT] [int] NULL,
       [EXEC_BY_CONTROL_ENGINE] [smallint] NULL,
CONSTRAINT [PK_ETL_HISTORY] PRIMARY KEY NONCLUSTERED
(
       [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
 
GO
 
ALTER TABLE [MWH].[ETL_HISTORY] ADD  CONSTRAINT [ETL_HISTORY_INSERT_CNT_DF]  DEFAULT ((0)) FOR [INSERT_CNT]
GO
 
ALTER TABLE [MWH].[ETL_HISTORY] ADD  CONSTRAINT [ETL_HISTORY_UPDATE_CNT_DF]  DEFAULT ((0)) FOR [UPDATE_CNT]
GO
 
ALTER TABLE [MWH].[ETL_HISTORY] ADD  CONSTRAINT [ETL_HISTORY_LST_MOD_USER_DF]  DEFAULT (user_name()) FOR [LST_MOD_USER]
GO
 
ALTER TABLE [MWH].[ETL_HISTORY] ADD  CONSTRAINT [RECORD_TEST_DATA_INSERT_DTTM_DF]  DEFAULT (getdate()) FOR [INSERT_DTTM]
GO
 
ALTER TABLE [MWH].[ETL_HISTORY] ADD  CONSTRAINT [RECORD_TEST_DATA_UPDATE_DTTM_DF]  DEFAULT (getdate()) FOR [UPDATE_DTTM]
GO
 
ALTER TABLE [MWH].[ETL_HISTORY] ADD  CONSTRAINT [ETL_HISTORY_ERR_NUM_DF]  DEFAULT ((0)) FOR [ERR_NUM]
GO
 
ALTER TABLE [MWH].[ETL_HISTORY] ADD  CONSTRAINT [ETL_HISTORY_DELETE_CNT_DF]  DEFAULT ((0)) FOR [DELETE_CNT]
GO
