schema = (
  'ID',
  'INSERT_DTTM',
  'UPDATE_DTTM',
  'LST_MOD_USER',
  'MSTR_LOAD_ID',
  'D_STAFF_ID',
  'EMPLOYEE_LAST_NAME',
  'EMPLOYEE_FIRST_NAME',
  'EMPLOYEE_EMAIL',
  'EMPLOYEE_PHONE',
  'EMPLOYEE_CELL_PHONE',
  'EMPLOYEE_PASSWORD'
)
